// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs/structs.proto

#include "structs/structs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace structs {
PROTOBUF_CONSTEXPR StructField::StructField(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.structs_transient_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StructFieldDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StructFieldDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StructFieldDefaultTypeInternal() {}
  union {
    StructField _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StructFieldDefaultTypeInternal _StructField_default_instance_;
PROTOBUF_CONSTEXPR StructSchema::StructSchema(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.java_package_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.java_class_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StructSchemaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StructSchemaDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StructSchemaDefaultTypeInternal() {}
  union {
    StructSchema _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StructSchemaDefaultTypeInternal _StructSchema_default_instance_;
}  // namespace structs
static ::_pb::Metadata file_level_metadata_structs_2fstructs_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_structs_2fstructs_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_structs_2fstructs_2eproto = nullptr;

const uint32_t TableStruct_structs_2fstructs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::structs::StructField, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::structs::StructField, _impl_.path_),
  PROTOBUF_FIELD_OFFSET(::structs::StructField, _impl_.structs_transient_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::structs::StructSchema, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::structs::StructSchema, _impl_.message_name_),
  PROTOBUF_FIELD_OFFSET(::structs::StructSchema, _impl_.java_package_),
  PROTOBUF_FIELD_OFFSET(::structs::StructSchema, _impl_.java_class_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::structs::StructField)},
  { 8, -1, -1, sizeof(::structs::StructSchema)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::structs::_StructField_default_instance_._instance,
  &::structs::_StructSchema_default_instance_._instance,
};

const char descriptor_table_protodef_structs_2fstructs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025structs/structs.proto\022\007structs\"6\n\013Stru"
  "ctField\022\014\n\004path\030\001 \001(\t\022\031\n\021structs_transie"
  "nt\030\002 \001(\010\"N\n\014StructSchema\022\024\n\014message_name"
  "\030\001 \001(\t\022\024\n\014java_package\030\002 \001(\t\022\022\n\njava_cla"
  "ss\030\003 \001(\tb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_structs_2fstructs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_structs_2fstructs_2eproto = {
    false, false, 176, descriptor_table_protodef_structs_2fstructs_2eproto,
    "structs/structs.proto",
    &descriptor_table_structs_2fstructs_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_structs_2fstructs_2eproto::offsets,
    file_level_metadata_structs_2fstructs_2eproto, file_level_enum_descriptors_structs_2fstructs_2eproto,
    file_level_service_descriptors_structs_2fstructs_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_structs_2fstructs_2eproto_getter() {
  return &descriptor_table_structs_2fstructs_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_structs_2fstructs_2eproto(&descriptor_table_structs_2fstructs_2eproto);
namespace structs {

// ===================================================================

class StructField::_Internal {
 public:
};

StructField::StructField(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:structs.StructField)
}
StructField::StructField(const StructField& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StructField* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.path_){}
    , decltype(_impl_.structs_transient_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_path().empty()) {
    _this->_impl_.path_.Set(from._internal_path(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.structs_transient_ = from._impl_.structs_transient_;
  // @@protoc_insertion_point(copy_constructor:structs.StructField)
}

inline void StructField::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.path_){}
    , decltype(_impl_.structs_transient_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

StructField::~StructField() {
  // @@protoc_insertion_point(destructor:structs.StructField)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StructField::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.path_.Destroy();
}

void StructField::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StructField::Clear() {
// @@protoc_insertion_point(message_clear_start:structs.StructField)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _impl_.structs_transient_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StructField::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "structs.StructField.path"));
        } else
          goto handle_unusual;
        continue;
      // bool structs_transient = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.structs_transient_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StructField::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:structs.StructField)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string path = 1;
  if (!this->_internal_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "structs.StructField.path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path(), target);
  }

  // bool structs_transient = 2;
  if (this->_internal_structs_transient() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_structs_transient(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:structs.StructField)
  return target;
}

size_t StructField::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:structs.StructField)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string path = 1;
  if (!this->_internal_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  // bool structs_transient = 2;
  if (this->_internal_structs_transient() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StructField::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StructField::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StructField::GetClassData() const { return &_class_data_; }


void StructField::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StructField*>(&to_msg);
  auto& from = static_cast<const StructField&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:structs.StructField)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  if (from._internal_structs_transient() != 0) {
    _this->_internal_set_structs_transient(from._internal_structs_transient());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StructField::CopyFrom(const StructField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:structs.StructField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StructField::IsInitialized() const {
  return true;
}

void StructField::InternalSwap(StructField* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.path_, lhs_arena,
      &other->_impl_.path_, rhs_arena
  );
  swap(_impl_.structs_transient_, other->_impl_.structs_transient_);
}

::PROTOBUF_NAMESPACE_ID::Metadata StructField::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_structs_2fstructs_2eproto_getter, &descriptor_table_structs_2fstructs_2eproto_once,
      file_level_metadata_structs_2fstructs_2eproto[0]);
}

// ===================================================================

class StructSchema::_Internal {
 public:
};

StructSchema::StructSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:structs.StructSchema)
}
StructSchema::StructSchema(const StructSchema& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StructSchema* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_name_){}
    , decltype(_impl_.java_package_){}
    , decltype(_impl_.java_class_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_name().empty()) {
    _this->_impl_.message_name_.Set(from._internal_message_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.java_package_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.java_package_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_java_package().empty()) {
    _this->_impl_.java_package_.Set(from._internal_java_package(), 
      _this->GetArenaForAllocation());
  }
  _impl_.java_class_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.java_class_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_java_class().empty()) {
    _this->_impl_.java_class_.Set(from._internal_java_class(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:structs.StructSchema)
}

inline void StructSchema::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_name_){}
    , decltype(_impl_.java_package_){}
    , decltype(_impl_.java_class_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.java_package_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.java_package_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.java_class_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.java_class_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

StructSchema::~StructSchema() {
  // @@protoc_insertion_point(destructor:structs.StructSchema)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StructSchema::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_name_.Destroy();
  _impl_.java_package_.Destroy();
  _impl_.java_class_.Destroy();
}

void StructSchema::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StructSchema::Clear() {
// @@protoc_insertion_point(message_clear_start:structs.StructSchema)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_name_.ClearToEmpty();
  _impl_.java_package_.ClearToEmpty();
  _impl_.java_class_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StructSchema::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string message_name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "structs.StructSchema.message_name"));
        } else
          goto handle_unusual;
        continue;
      // string java_package = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_java_package();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "structs.StructSchema.java_package"));
        } else
          goto handle_unusual;
        continue;
      // string java_class = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_java_class();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "structs.StructSchema.java_class"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StructSchema::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:structs.StructSchema)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string message_name = 1;
  if (!this->_internal_message_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_name().data(), static_cast<int>(this->_internal_message_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "structs.StructSchema.message_name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message_name(), target);
  }

  // string java_package = 2;
  if (!this->_internal_java_package().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_java_package().data(), static_cast<int>(this->_internal_java_package().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "structs.StructSchema.java_package");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_java_package(), target);
  }

  // string java_class = 3;
  if (!this->_internal_java_class().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_java_class().data(), static_cast<int>(this->_internal_java_class().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "structs.StructSchema.java_class");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_java_class(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:structs.StructSchema)
  return target;
}

size_t StructSchema::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:structs.StructSchema)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_name = 1;
  if (!this->_internal_message_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_name());
  }

  // string java_package = 2;
  if (!this->_internal_java_package().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_java_package());
  }

  // string java_class = 3;
  if (!this->_internal_java_class().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_java_class());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StructSchema::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StructSchema::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StructSchema::GetClassData() const { return &_class_data_; }


void StructSchema::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StructSchema*>(&to_msg);
  auto& from = static_cast<const StructSchema&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:structs.StructSchema)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_name().empty()) {
    _this->_internal_set_message_name(from._internal_message_name());
  }
  if (!from._internal_java_package().empty()) {
    _this->_internal_set_java_package(from._internal_java_package());
  }
  if (!from._internal_java_class().empty()) {
    _this->_internal_set_java_class(from._internal_java_class());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StructSchema::CopyFrom(const StructSchema& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:structs.StructSchema)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StructSchema::IsInitialized() const {
  return true;
}

void StructSchema::InternalSwap(StructSchema* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_name_, lhs_arena,
      &other->_impl_.message_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.java_package_, lhs_arena,
      &other->_impl_.java_package_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.java_class_, lhs_arena,
      &other->_impl_.java_class_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata StructSchema::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_structs_2fstructs_2eproto_getter, &descriptor_table_structs_2fstructs_2eproto_once,
      file_level_metadata_structs_2fstructs_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace structs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::structs::StructField*
Arena::CreateMaybeMessage< ::structs::StructField >(Arena* arena) {
  return Arena::CreateMessageInternal< ::structs::StructField >(arena);
}
template<> PROTOBUF_NOINLINE ::structs::StructSchema*
Arena::CreateMaybeMessage< ::structs::StructSchema >(Arena* arena) {
  return Arena::CreateMessageInternal< ::structs::StructSchema >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
