java_library(
    name = "structs_runtime",
    srcs = glob(
        [
            "**/*.java",
        ],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/jvm/com/scylladb:java_driver_core",
        "//3rdparty/jvm/com/google/guava",
    ],
)
