// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: structs/cassandra/cassandra.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_structs_2fcassandra_2fcassandra_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_structs_2fcassandra_2fcassandra_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_structs_2fcassandra_2fcassandra_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_structs_2fcassandra_2fcassandra_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_structs_2fcassandra_2fcassandra_2eproto;
namespace structs {
class CassandraField;
class CassandraFieldDefaultTypeInternal;
extern CassandraFieldDefaultTypeInternal _CassandraField_default_instance_;
class CassandraSchema;
class CassandraSchemaDefaultTypeInternal;
extern CassandraSchemaDefaultTypeInternal _CassandraSchema_default_instance_;
class CassandraSchemas;
class CassandraSchemasDefaultTypeInternal;
extern CassandraSchemasDefaultTypeInternal _CassandraSchemas_default_instance_;
}  // namespace structs
PROTOBUF_NAMESPACE_OPEN
template<> ::structs::CassandraField* Arena::CreateMaybeMessage<::structs::CassandraField>(Arena*);
template<> ::structs::CassandraSchema* Arena::CreateMaybeMessage<::structs::CassandraSchema>(Arena*);
template<> ::structs::CassandraSchemas* Arena::CreateMaybeMessage<::structs::CassandraSchemas>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace structs {

enum RepeatedHandler : int {
  LIST = 0,
  FROZEN_LIST = 1,
  BYTES = 2,
  FROZEN_SET = 3,
  SET = 4,
  RepeatedHandler_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  RepeatedHandler_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool RepeatedHandler_IsValid(int value);
constexpr RepeatedHandler RepeatedHandler_MIN = LIST;
constexpr RepeatedHandler RepeatedHandler_MAX = SET;
constexpr int RepeatedHandler_ARRAYSIZE = RepeatedHandler_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RepeatedHandler_descriptor();
template<typename T>
inline const std::string& RepeatedHandler_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RepeatedHandler>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RepeatedHandler_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RepeatedHandler_descriptor(), enum_t_value);
}
inline bool RepeatedHandler_Parse(
    const std::string& name, RepeatedHandler* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RepeatedHandler>(
    RepeatedHandler_descriptor(), name, value);
}
// ===================================================================

class CassandraField :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:structs.CassandraField) */ {
 public:
  CassandraField();
  virtual ~CassandraField();

  CassandraField(const CassandraField& from);
  CassandraField(CassandraField&& from) noexcept
    : CassandraField() {
    *this = ::std::move(from);
  }

  inline CassandraField& operator=(const CassandraField& from) {
    CopyFrom(from);
    return *this;
  }
  inline CassandraField& operator=(CassandraField&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CassandraField& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CassandraField* internal_default_instance() {
    return reinterpret_cast<const CassandraField*>(
               &_CassandraField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CassandraField& a, CassandraField& b) {
    a.Swap(&b);
  }
  inline void Swap(CassandraField* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CassandraField* New() const final {
    return CreateMaybeMessage<CassandraField>(nullptr);
  }

  CassandraField* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CassandraField>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CassandraField& from);
  void MergeFrom(const CassandraField& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CassandraField* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "structs.CassandraField";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_structs_2fcassandra_2fcassandra_2eproto);
    return ::descriptor_table_structs_2fcassandra_2fcassandra_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 1,
    kFieldNameFieldNumber = 5,
    kIsIdFieldNumber = 2,
    kIsBytesFieldNumber = 3,
    kIsTransientFieldNumber = 4,
    kRepeatedHandlingFieldNumber = 6,
    kIdCardinalityFieldNumber = 7,
  };
  // string path = 1;
  void clear_path();
  const std::string& path() const;
  void set_path(const std::string& value);
  void set_path(std::string&& value);
  void set_path(const char* value);
  void set_path(const char* value, size_t size);
  std::string* mutable_path();
  std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // string field_name = 5;
  void clear_field_name();
  const std::string& field_name() const;
  void set_field_name(const std::string& value);
  void set_field_name(std::string&& value);
  void set_field_name(const char* value);
  void set_field_name(const char* value, size_t size);
  std::string* mutable_field_name();
  std::string* release_field_name();
  void set_allocated_field_name(std::string* field_name);
  private:
  const std::string& _internal_field_name() const;
  void _internal_set_field_name(const std::string& value);
  std::string* _internal_mutable_field_name();
  public:

  // bool is_id = 2;
  void clear_is_id();
  bool is_id() const;
  void set_is_id(bool value);
  private:
  bool _internal_is_id() const;
  void _internal_set_is_id(bool value);
  public:

  // bool is_bytes = 3;
  void clear_is_bytes();
  bool is_bytes() const;
  void set_is_bytes(bool value);
  private:
  bool _internal_is_bytes() const;
  void _internal_set_is_bytes(bool value);
  public:

  // bool is_transient = 4;
  void clear_is_transient();
  bool is_transient() const;
  void set_is_transient(bool value);
  private:
  bool _internal_is_transient() const;
  void _internal_set_is_transient(bool value);
  public:

  // .structs.RepeatedHandler repeated_handling = 6;
  void clear_repeated_handling();
  ::structs::RepeatedHandler repeated_handling() const;
  void set_repeated_handling(::structs::RepeatedHandler value);
  private:
  ::structs::RepeatedHandler _internal_repeated_handling() const;
  void _internal_set_repeated_handling(::structs::RepeatedHandler value);
  public:

  // int32 id_cardinality = 7;
  void clear_id_cardinality();
  ::PROTOBUF_NAMESPACE_ID::int32 id_cardinality() const;
  void set_id_cardinality(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id_cardinality() const;
  void _internal_set_id_cardinality(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:structs.CassandraField)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr field_name_;
  bool is_id_;
  bool is_bytes_;
  bool is_transient_;
  int repeated_handling_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_cardinality_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_structs_2fcassandra_2fcassandra_2eproto;
};
// -------------------------------------------------------------------

class CassandraSchema :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:structs.CassandraSchema) */ {
 public:
  CassandraSchema();
  virtual ~CassandraSchema();

  CassandraSchema(const CassandraSchema& from);
  CassandraSchema(CassandraSchema&& from) noexcept
    : CassandraSchema() {
    *this = ::std::move(from);
  }

  inline CassandraSchema& operator=(const CassandraSchema& from) {
    CopyFrom(from);
    return *this;
  }
  inline CassandraSchema& operator=(CassandraSchema&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CassandraSchema& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CassandraSchema* internal_default_instance() {
    return reinterpret_cast<const CassandraSchema*>(
               &_CassandraSchema_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CassandraSchema& a, CassandraSchema& b) {
    a.Swap(&b);
  }
  inline void Swap(CassandraSchema* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CassandraSchema* New() const final {
    return CreateMaybeMessage<CassandraSchema>(nullptr);
  }

  CassandraSchema* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CassandraSchema>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CassandraSchema& from);
  void MergeFrom(const CassandraSchema& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CassandraSchema* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "structs.CassandraSchema";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_structs_2fcassandra_2fcassandra_2eproto);
    return ::descriptor_table_structs_2fcassandra_2fcassandra_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldsFieldNumber = 3,
    kMessageNameFieldNumber = 1,
    kTableNameFieldNumber = 2,
    kCompactionStrategyFieldNumber = 4,
    kCompressionStrategyFieldNumber = 5,
    kJavaPackageFieldNumber = 6,
    kJavaClassFieldNumber = 7,
  };
  // repeated .structs.CassandraField fields = 3;
  int fields_size() const;
  private:
  int _internal_fields_size() const;
  public:
  void clear_fields();
  ::structs::CassandraField* mutable_fields(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraField >*
      mutable_fields();
  private:
  const ::structs::CassandraField& _internal_fields(int index) const;
  ::structs::CassandraField* _internal_add_fields();
  public:
  const ::structs::CassandraField& fields(int index) const;
  ::structs::CassandraField* add_fields();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraField >&
      fields() const;

  // string message_name = 1;
  void clear_message_name();
  const std::string& message_name() const;
  void set_message_name(const std::string& value);
  void set_message_name(std::string&& value);
  void set_message_name(const char* value);
  void set_message_name(const char* value, size_t size);
  std::string* mutable_message_name();
  std::string* release_message_name();
  void set_allocated_message_name(std::string* message_name);
  private:
  const std::string& _internal_message_name() const;
  void _internal_set_message_name(const std::string& value);
  std::string* _internal_mutable_message_name();
  public:

  // string table_name = 2;
  void clear_table_name();
  const std::string& table_name() const;
  void set_table_name(const std::string& value);
  void set_table_name(std::string&& value);
  void set_table_name(const char* value);
  void set_table_name(const char* value, size_t size);
  std::string* mutable_table_name();
  std::string* release_table_name();
  void set_allocated_table_name(std::string* table_name);
  private:
  const std::string& _internal_table_name() const;
  void _internal_set_table_name(const std::string& value);
  std::string* _internal_mutable_table_name();
  public:

  // string compaction_strategy = 4;
  void clear_compaction_strategy();
  const std::string& compaction_strategy() const;
  void set_compaction_strategy(const std::string& value);
  void set_compaction_strategy(std::string&& value);
  void set_compaction_strategy(const char* value);
  void set_compaction_strategy(const char* value, size_t size);
  std::string* mutable_compaction_strategy();
  std::string* release_compaction_strategy();
  void set_allocated_compaction_strategy(std::string* compaction_strategy);
  private:
  const std::string& _internal_compaction_strategy() const;
  void _internal_set_compaction_strategy(const std::string& value);
  std::string* _internal_mutable_compaction_strategy();
  public:

  // string compression_strategy = 5;
  void clear_compression_strategy();
  const std::string& compression_strategy() const;
  void set_compression_strategy(const std::string& value);
  void set_compression_strategy(std::string&& value);
  void set_compression_strategy(const char* value);
  void set_compression_strategy(const char* value, size_t size);
  std::string* mutable_compression_strategy();
  std::string* release_compression_strategy();
  void set_allocated_compression_strategy(std::string* compression_strategy);
  private:
  const std::string& _internal_compression_strategy() const;
  void _internal_set_compression_strategy(const std::string& value);
  std::string* _internal_mutable_compression_strategy();
  public:

  // string java_package = 6;
  void clear_java_package();
  const std::string& java_package() const;
  void set_java_package(const std::string& value);
  void set_java_package(std::string&& value);
  void set_java_package(const char* value);
  void set_java_package(const char* value, size_t size);
  std::string* mutable_java_package();
  std::string* release_java_package();
  void set_allocated_java_package(std::string* java_package);
  private:
  const std::string& _internal_java_package() const;
  void _internal_set_java_package(const std::string& value);
  std::string* _internal_mutable_java_package();
  public:

  // string java_class = 7;
  void clear_java_class();
  const std::string& java_class() const;
  void set_java_class(const std::string& value);
  void set_java_class(std::string&& value);
  void set_java_class(const char* value);
  void set_java_class(const char* value, size_t size);
  std::string* mutable_java_class();
  std::string* release_java_class();
  void set_allocated_java_class(std::string* java_class);
  private:
  const std::string& _internal_java_class() const;
  void _internal_set_java_class(const std::string& value);
  std::string* _internal_mutable_java_class();
  public:

  // @@protoc_insertion_point(class_scope:structs.CassandraSchema)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraField > fields_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr table_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compaction_strategy_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr compression_strategy_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr java_package_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr java_class_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_structs_2fcassandra_2fcassandra_2eproto;
};
// -------------------------------------------------------------------

class CassandraSchemas :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:structs.CassandraSchemas) */ {
 public:
  CassandraSchemas();
  virtual ~CassandraSchemas();

  CassandraSchemas(const CassandraSchemas& from);
  CassandraSchemas(CassandraSchemas&& from) noexcept
    : CassandraSchemas() {
    *this = ::std::move(from);
  }

  inline CassandraSchemas& operator=(const CassandraSchemas& from) {
    CopyFrom(from);
    return *this;
  }
  inline CassandraSchemas& operator=(CassandraSchemas&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CassandraSchemas& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CassandraSchemas* internal_default_instance() {
    return reinterpret_cast<const CassandraSchemas*>(
               &_CassandraSchemas_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CassandraSchemas& a, CassandraSchemas& b) {
    a.Swap(&b);
  }
  inline void Swap(CassandraSchemas* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CassandraSchemas* New() const final {
    return CreateMaybeMessage<CassandraSchemas>(nullptr);
  }

  CassandraSchemas* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CassandraSchemas>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CassandraSchemas& from);
  void MergeFrom(const CassandraSchemas& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CassandraSchemas* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "structs.CassandraSchemas";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_structs_2fcassandra_2fcassandra_2eproto);
    return ::descriptor_table_structs_2fcassandra_2fcassandra_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSchemaFieldNumber = 1,
  };
  // repeated .structs.CassandraSchema schema = 1;
  int schema_size() const;
  private:
  int _internal_schema_size() const;
  public:
  void clear_schema();
  ::structs::CassandraSchema* mutable_schema(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraSchema >*
      mutable_schema();
  private:
  const ::structs::CassandraSchema& _internal_schema(int index) const;
  ::structs::CassandraSchema* _internal_add_schema();
  public:
  const ::structs::CassandraSchema& schema(int index) const;
  ::structs::CassandraSchema* add_schema();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraSchema >&
      schema() const;

  // @@protoc_insertion_point(class_scope:structs.CassandraSchemas)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraSchema > schema_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_structs_2fcassandra_2fcassandra_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CassandraField

// string path = 1;
inline void CassandraField::clear_path() {
  path_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraField::path() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.path)
  return _internal_path();
}
inline void CassandraField::set_path(const std::string& value) {
  _internal_set_path(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.path)
}
inline std::string* CassandraField::mutable_path() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraField.path)
  return _internal_mutable_path();
}
inline const std::string& CassandraField::_internal_path() const {
  return path_.GetNoArena();
}
inline void CassandraField::_internal_set_path(const std::string& value) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraField::set_path(std::string&& value) {
  
  path_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraField.path)
}
inline void CassandraField::set_path(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraField.path)
}
inline void CassandraField::set_path(const char* value, size_t size) {
  
  path_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraField.path)
}
inline std::string* CassandraField::_internal_mutable_path() {
  
  return path_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraField::release_path() {
  // @@protoc_insertion_point(field_release:structs.CassandraField.path)
  
  return path_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraField::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraField.path)
}

// bool is_id = 2;
inline void CassandraField::clear_is_id() {
  is_id_ = false;
}
inline bool CassandraField::_internal_is_id() const {
  return is_id_;
}
inline bool CassandraField::is_id() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.is_id)
  return _internal_is_id();
}
inline void CassandraField::_internal_set_is_id(bool value) {
  
  is_id_ = value;
}
inline void CassandraField::set_is_id(bool value) {
  _internal_set_is_id(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.is_id)
}

// int32 id_cardinality = 7;
inline void CassandraField::clear_id_cardinality() {
  id_cardinality_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CassandraField::_internal_id_cardinality() const {
  return id_cardinality_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CassandraField::id_cardinality() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.id_cardinality)
  return _internal_id_cardinality();
}
inline void CassandraField::_internal_set_id_cardinality(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_cardinality_ = value;
}
inline void CassandraField::set_id_cardinality(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id_cardinality(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.id_cardinality)
}

// bool is_bytes = 3;
inline void CassandraField::clear_is_bytes() {
  is_bytes_ = false;
}
inline bool CassandraField::_internal_is_bytes() const {
  return is_bytes_;
}
inline bool CassandraField::is_bytes() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.is_bytes)
  return _internal_is_bytes();
}
inline void CassandraField::_internal_set_is_bytes(bool value) {
  
  is_bytes_ = value;
}
inline void CassandraField::set_is_bytes(bool value) {
  _internal_set_is_bytes(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.is_bytes)
}

// bool is_transient = 4;
inline void CassandraField::clear_is_transient() {
  is_transient_ = false;
}
inline bool CassandraField::_internal_is_transient() const {
  return is_transient_;
}
inline bool CassandraField::is_transient() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.is_transient)
  return _internal_is_transient();
}
inline void CassandraField::_internal_set_is_transient(bool value) {
  
  is_transient_ = value;
}
inline void CassandraField::set_is_transient(bool value) {
  _internal_set_is_transient(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.is_transient)
}

// string field_name = 5;
inline void CassandraField::clear_field_name() {
  field_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraField::field_name() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.field_name)
  return _internal_field_name();
}
inline void CassandraField::set_field_name(const std::string& value) {
  _internal_set_field_name(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.field_name)
}
inline std::string* CassandraField::mutable_field_name() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraField.field_name)
  return _internal_mutable_field_name();
}
inline const std::string& CassandraField::_internal_field_name() const {
  return field_name_.GetNoArena();
}
inline void CassandraField::_internal_set_field_name(const std::string& value) {
  
  field_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraField::set_field_name(std::string&& value) {
  
  field_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraField.field_name)
}
inline void CassandraField::set_field_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  field_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraField.field_name)
}
inline void CassandraField::set_field_name(const char* value, size_t size) {
  
  field_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraField.field_name)
}
inline std::string* CassandraField::_internal_mutable_field_name() {
  
  return field_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraField::release_field_name() {
  // @@protoc_insertion_point(field_release:structs.CassandraField.field_name)
  
  return field_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraField::set_allocated_field_name(std::string* field_name) {
  if (field_name != nullptr) {
    
  } else {
    
  }
  field_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), field_name);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraField.field_name)
}

// .structs.RepeatedHandler repeated_handling = 6;
inline void CassandraField::clear_repeated_handling() {
  repeated_handling_ = 0;
}
inline ::structs::RepeatedHandler CassandraField::_internal_repeated_handling() const {
  return static_cast< ::structs::RepeatedHandler >(repeated_handling_);
}
inline ::structs::RepeatedHandler CassandraField::repeated_handling() const {
  // @@protoc_insertion_point(field_get:structs.CassandraField.repeated_handling)
  return _internal_repeated_handling();
}
inline void CassandraField::_internal_set_repeated_handling(::structs::RepeatedHandler value) {
  
  repeated_handling_ = value;
}
inline void CassandraField::set_repeated_handling(::structs::RepeatedHandler value) {
  _internal_set_repeated_handling(value);
  // @@protoc_insertion_point(field_set:structs.CassandraField.repeated_handling)
}

// -------------------------------------------------------------------

// CassandraSchema

// string message_name = 1;
inline void CassandraSchema::clear_message_name() {
  message_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraSchema::message_name() const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.message_name)
  return _internal_message_name();
}
inline void CassandraSchema::set_message_name(const std::string& value) {
  _internal_set_message_name(value);
  // @@protoc_insertion_point(field_set:structs.CassandraSchema.message_name)
}
inline std::string* CassandraSchema::mutable_message_name() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.message_name)
  return _internal_mutable_message_name();
}
inline const std::string& CassandraSchema::_internal_message_name() const {
  return message_name_.GetNoArena();
}
inline void CassandraSchema::_internal_set_message_name(const std::string& value) {
  
  message_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraSchema::set_message_name(std::string&& value) {
  
  message_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraSchema.message_name)
}
inline void CassandraSchema::set_message_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraSchema.message_name)
}
inline void CassandraSchema::set_message_name(const char* value, size_t size) {
  
  message_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraSchema.message_name)
}
inline std::string* CassandraSchema::_internal_mutable_message_name() {
  
  return message_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraSchema::release_message_name() {
  // @@protoc_insertion_point(field_release:structs.CassandraSchema.message_name)
  
  return message_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraSchema::set_allocated_message_name(std::string* message_name) {
  if (message_name != nullptr) {
    
  } else {
    
  }
  message_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message_name);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraSchema.message_name)
}

// string table_name = 2;
inline void CassandraSchema::clear_table_name() {
  table_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraSchema::table_name() const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.table_name)
  return _internal_table_name();
}
inline void CassandraSchema::set_table_name(const std::string& value) {
  _internal_set_table_name(value);
  // @@protoc_insertion_point(field_set:structs.CassandraSchema.table_name)
}
inline std::string* CassandraSchema::mutable_table_name() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.table_name)
  return _internal_mutable_table_name();
}
inline const std::string& CassandraSchema::_internal_table_name() const {
  return table_name_.GetNoArena();
}
inline void CassandraSchema::_internal_set_table_name(const std::string& value) {
  
  table_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraSchema::set_table_name(std::string&& value) {
  
  table_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraSchema.table_name)
}
inline void CassandraSchema::set_table_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  table_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraSchema.table_name)
}
inline void CassandraSchema::set_table_name(const char* value, size_t size) {
  
  table_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraSchema.table_name)
}
inline std::string* CassandraSchema::_internal_mutable_table_name() {
  
  return table_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraSchema::release_table_name() {
  // @@protoc_insertion_point(field_release:structs.CassandraSchema.table_name)
  
  return table_name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraSchema::set_allocated_table_name(std::string* table_name) {
  if (table_name != nullptr) {
    
  } else {
    
  }
  table_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), table_name);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraSchema.table_name)
}

// repeated .structs.CassandraField fields = 3;
inline int CassandraSchema::_internal_fields_size() const {
  return fields_.size();
}
inline int CassandraSchema::fields_size() const {
  return _internal_fields_size();
}
inline void CassandraSchema::clear_fields() {
  fields_.Clear();
}
inline ::structs::CassandraField* CassandraSchema::mutable_fields(int index) {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.fields)
  return fields_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraField >*
CassandraSchema::mutable_fields() {
  // @@protoc_insertion_point(field_mutable_list:structs.CassandraSchema.fields)
  return &fields_;
}
inline const ::structs::CassandraField& CassandraSchema::_internal_fields(int index) const {
  return fields_.Get(index);
}
inline const ::structs::CassandraField& CassandraSchema::fields(int index) const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.fields)
  return _internal_fields(index);
}
inline ::structs::CassandraField* CassandraSchema::_internal_add_fields() {
  return fields_.Add();
}
inline ::structs::CassandraField* CassandraSchema::add_fields() {
  // @@protoc_insertion_point(field_add:structs.CassandraSchema.fields)
  return _internal_add_fields();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraField >&
CassandraSchema::fields() const {
  // @@protoc_insertion_point(field_list:structs.CassandraSchema.fields)
  return fields_;
}

// string compaction_strategy = 4;
inline void CassandraSchema::clear_compaction_strategy() {
  compaction_strategy_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraSchema::compaction_strategy() const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.compaction_strategy)
  return _internal_compaction_strategy();
}
inline void CassandraSchema::set_compaction_strategy(const std::string& value) {
  _internal_set_compaction_strategy(value);
  // @@protoc_insertion_point(field_set:structs.CassandraSchema.compaction_strategy)
}
inline std::string* CassandraSchema::mutable_compaction_strategy() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.compaction_strategy)
  return _internal_mutable_compaction_strategy();
}
inline const std::string& CassandraSchema::_internal_compaction_strategy() const {
  return compaction_strategy_.GetNoArena();
}
inline void CassandraSchema::_internal_set_compaction_strategy(const std::string& value) {
  
  compaction_strategy_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraSchema::set_compaction_strategy(std::string&& value) {
  
  compaction_strategy_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraSchema.compaction_strategy)
}
inline void CassandraSchema::set_compaction_strategy(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  compaction_strategy_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraSchema.compaction_strategy)
}
inline void CassandraSchema::set_compaction_strategy(const char* value, size_t size) {
  
  compaction_strategy_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraSchema.compaction_strategy)
}
inline std::string* CassandraSchema::_internal_mutable_compaction_strategy() {
  
  return compaction_strategy_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraSchema::release_compaction_strategy() {
  // @@protoc_insertion_point(field_release:structs.CassandraSchema.compaction_strategy)
  
  return compaction_strategy_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraSchema::set_allocated_compaction_strategy(std::string* compaction_strategy) {
  if (compaction_strategy != nullptr) {
    
  } else {
    
  }
  compaction_strategy_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), compaction_strategy);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraSchema.compaction_strategy)
}

// string compression_strategy = 5;
inline void CassandraSchema::clear_compression_strategy() {
  compression_strategy_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraSchema::compression_strategy() const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.compression_strategy)
  return _internal_compression_strategy();
}
inline void CassandraSchema::set_compression_strategy(const std::string& value) {
  _internal_set_compression_strategy(value);
  // @@protoc_insertion_point(field_set:structs.CassandraSchema.compression_strategy)
}
inline std::string* CassandraSchema::mutable_compression_strategy() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.compression_strategy)
  return _internal_mutable_compression_strategy();
}
inline const std::string& CassandraSchema::_internal_compression_strategy() const {
  return compression_strategy_.GetNoArena();
}
inline void CassandraSchema::_internal_set_compression_strategy(const std::string& value) {
  
  compression_strategy_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraSchema::set_compression_strategy(std::string&& value) {
  
  compression_strategy_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraSchema.compression_strategy)
}
inline void CassandraSchema::set_compression_strategy(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  compression_strategy_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraSchema.compression_strategy)
}
inline void CassandraSchema::set_compression_strategy(const char* value, size_t size) {
  
  compression_strategy_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraSchema.compression_strategy)
}
inline std::string* CassandraSchema::_internal_mutable_compression_strategy() {
  
  return compression_strategy_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraSchema::release_compression_strategy() {
  // @@protoc_insertion_point(field_release:structs.CassandraSchema.compression_strategy)
  
  return compression_strategy_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraSchema::set_allocated_compression_strategy(std::string* compression_strategy) {
  if (compression_strategy != nullptr) {
    
  } else {
    
  }
  compression_strategy_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), compression_strategy);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraSchema.compression_strategy)
}

// string java_package = 6;
inline void CassandraSchema::clear_java_package() {
  java_package_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraSchema::java_package() const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.java_package)
  return _internal_java_package();
}
inline void CassandraSchema::set_java_package(const std::string& value) {
  _internal_set_java_package(value);
  // @@protoc_insertion_point(field_set:structs.CassandraSchema.java_package)
}
inline std::string* CassandraSchema::mutable_java_package() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.java_package)
  return _internal_mutable_java_package();
}
inline const std::string& CassandraSchema::_internal_java_package() const {
  return java_package_.GetNoArena();
}
inline void CassandraSchema::_internal_set_java_package(const std::string& value) {
  
  java_package_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraSchema::set_java_package(std::string&& value) {
  
  java_package_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraSchema.java_package)
}
inline void CassandraSchema::set_java_package(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  java_package_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraSchema.java_package)
}
inline void CassandraSchema::set_java_package(const char* value, size_t size) {
  
  java_package_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraSchema.java_package)
}
inline std::string* CassandraSchema::_internal_mutable_java_package() {
  
  return java_package_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraSchema::release_java_package() {
  // @@protoc_insertion_point(field_release:structs.CassandraSchema.java_package)
  
  return java_package_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraSchema::set_allocated_java_package(std::string* java_package) {
  if (java_package != nullptr) {
    
  } else {
    
  }
  java_package_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), java_package);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraSchema.java_package)
}

// string java_class = 7;
inline void CassandraSchema::clear_java_class() {
  java_class_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& CassandraSchema::java_class() const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchema.java_class)
  return _internal_java_class();
}
inline void CassandraSchema::set_java_class(const std::string& value) {
  _internal_set_java_class(value);
  // @@protoc_insertion_point(field_set:structs.CassandraSchema.java_class)
}
inline std::string* CassandraSchema::mutable_java_class() {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchema.java_class)
  return _internal_mutable_java_class();
}
inline const std::string& CassandraSchema::_internal_java_class() const {
  return java_class_.GetNoArena();
}
inline void CassandraSchema::_internal_set_java_class(const std::string& value) {
  
  java_class_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void CassandraSchema::set_java_class(std::string&& value) {
  
  java_class_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:structs.CassandraSchema.java_class)
}
inline void CassandraSchema::set_java_class(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  java_class_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:structs.CassandraSchema.java_class)
}
inline void CassandraSchema::set_java_class(const char* value, size_t size) {
  
  java_class_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:structs.CassandraSchema.java_class)
}
inline std::string* CassandraSchema::_internal_mutable_java_class() {
  
  return java_class_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* CassandraSchema::release_java_class() {
  // @@protoc_insertion_point(field_release:structs.CassandraSchema.java_class)
  
  return java_class_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void CassandraSchema::set_allocated_java_class(std::string* java_class) {
  if (java_class != nullptr) {
    
  } else {
    
  }
  java_class_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), java_class);
  // @@protoc_insertion_point(field_set_allocated:structs.CassandraSchema.java_class)
}

// -------------------------------------------------------------------

// CassandraSchemas

// repeated .structs.CassandraSchema schema = 1;
inline int CassandraSchemas::_internal_schema_size() const {
  return schema_.size();
}
inline int CassandraSchemas::schema_size() const {
  return _internal_schema_size();
}
inline void CassandraSchemas::clear_schema() {
  schema_.Clear();
}
inline ::structs::CassandraSchema* CassandraSchemas::mutable_schema(int index) {
  // @@protoc_insertion_point(field_mutable:structs.CassandraSchemas.schema)
  return schema_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraSchema >*
CassandraSchemas::mutable_schema() {
  // @@protoc_insertion_point(field_mutable_list:structs.CassandraSchemas.schema)
  return &schema_;
}
inline const ::structs::CassandraSchema& CassandraSchemas::_internal_schema(int index) const {
  return schema_.Get(index);
}
inline const ::structs::CassandraSchema& CassandraSchemas::schema(int index) const {
  // @@protoc_insertion_point(field_get:structs.CassandraSchemas.schema)
  return _internal_schema(index);
}
inline ::structs::CassandraSchema* CassandraSchemas::_internal_add_schema() {
  return schema_.Add();
}
inline ::structs::CassandraSchema* CassandraSchemas::add_schema() {
  // @@protoc_insertion_point(field_add:structs.CassandraSchemas.schema)
  return _internal_add_schema();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::structs::CassandraSchema >&
CassandraSchemas::schema() const {
  // @@protoc_insertion_point(field_list:structs.CassandraSchemas.schema)
  return schema_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace structs

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::structs::RepeatedHandler> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::structs::RepeatedHandler>() {
  return ::structs::RepeatedHandler_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_structs_2fcassandra_2fcassandra_2eproto
